{% set version = '0.99.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-txcutr
  version: {{ version|replace("-", "_") }}

source:
  path: ../

build:
  merge_build_host: True  # [win]
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base  {{ r_base }}
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    # temporary fix for rtracklayer
    - openssl =1.1

  run:
    - r-base
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-rtracklayer
    # temporary fix for rtracklayer
    - openssl =1.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('txcutr')"           # [not win]
    - "\"%R%\" -e \"library('txcutr')\""  # [win]

about:
  home: https://github.com/mfansler/txcutr
  license: GPL-3
  summary: Methods for generating truncated transcriptome annotations and indexable sequences.

  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
